name: ann_env
channels:
  - akode
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0=py36_1000
  - attrs=19.1.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.0=py_0
  - bzip2=1.0.6=h1de35cc_1002
  - ca-certificates=2018.11.29=ha4d7672_0
  - certifi=2018.11.29=py36_1000
  - decorator=4.3.2=py_0
  - entrypoints=0.3=py36_1000
  - faiss-cpu=1.5.0=py36h04f5b5a_1
  - icu=58.2=h0a44026_1000
  - intel-openmp=2019.1=144
  - ipykernel=5.1.0=py36h24bf2e0_1002
  - ipython=7.3.0=py36h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.4.2=py_0
  - jedi=0.13.3=py36_0
  - jinja2=2.10=py_1
  - jpeg=9c=h1de35cc_1001
  - jsonschema=3.0.1=py36_0
  - jupyter=1.0.0=py_1
  - jupyter_client=5.2.4=py_3
  - jupyter_console=6.0.0=py_0
  - jupyter_contrib_core=0.3.3=py_2
  - jupyter_contrib_nbextensions=0.5.1=py36_0
  - jupyter_core=4.4.0=py_0
  - jupyter_highlight_selected_word=0.2.0=py36_1000
  - jupyter_latex_envs=1.4.4=py36_1000
  - jupyter_nbextensions_configurator=0.4.1=py36_0
  - libcxx=7.0.0=h2d50403_1
  - libffi=3.2.1=h0a44026_1005
  - libgfortran=3.0.1=0
  - libiconv=1.15=h1de35cc_1004
  - libpng=1.6.36=ha441bb4_1000
  - libsodium=1.0.16=h1de35cc_1001
  - libxml2=2.9.8=hf14e9c8_1005
  - libxslt=1.1.32=h33a18ac_1002
  - llvm-meta=7.0.0=0
  - lxml=4.3.2=py36h7166777_0
  - markupsafe=1.1.1=py36h1de35cc_0
  - mistune=0.8.4=py36h1de35cc_1000
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36h1de35cc_1
  - mkl_random=1.0.2=py36h1702cab_2
  - nbconvert=5.3.1=py_1
  - nbformat=4.4.0=py_1
  - ncurses=6.1=h0a44026_1002
  - nmslib=1.7.2=py36_0
  - notebook=5.7.4=py36_1
  - numpy=1.16.2=py36hacdab7b_0
  - numpy-base=1.16.2=py36h6575580_0
  - openssl=1.1.1b=h1de35cc_0
  - pandoc=2.6=1
  - pandocfilters=1.4.2=py_1
  - parso=0.3.4=py_0
  - pexpect=4.6.0=py36_1000
  - pickleshare=0.7.5=py36_1000
  - pip=19.0.3=py36_0
  - prometheus_client=0.6.0=py_0
  - prompt_toolkit=2.0.9=py_0
  - ptyprocess=0.6.0=py36_1000
  - pybind11=2.2.4=py36h04f5b5a_1000
  - pygments=2.3.1=py_0
  - pyqt=5.6.0=py36hc26a216_1008
  - pyrsistent=0.14.11=py36h1de35cc_0
  - python=3.6.7=h8dc6b48_1004
  - python-annoy=1.15.0=py36h0a44026_1000
  - python-dateutil=2.8.0=py_0
  - pyyaml=3.13=py36h1de35cc_1001
  - pyzmq=18.0.1=py36h4cc6ddd_0
  - qt=5.6.2=h822fa55_1013
  - qtconsole=4.4.3=py_0
  - readline=7.0=hcfe32e1_1001
  - rise=5.4.1=py36_1000
  - scikit-learn=0.20.2=py36h27c97d8_0
  - scipy=1.2.1=py36h1410ff5_0
  - send2trash=1.5.0=py_0
  - setuptools=40.8.0=py36_0
  - sip=4.18.1=py36h0a44026_1000
  - six=1.12.0=py36_1000
  - sqlite=3.26.0=h1765d9f_1000
  - terminado=0.8.1=py36_1001
  - testpath=0.4.2=py36_1000
  - tk=8.6.9=ha441bb4_1000
  - tornado=5.1.1=py36h1de35cc_1000
  - traitlets=4.3.2=py36_1000
  - wcwidth=0.1.7=py_1
  - webencodings=0.5.1=py_1
  - wheel=0.33.1=py36_0
  - widgetsnbextension=3.4.2=py36_1000
  - xz=5.2.4=h1de35cc_1001
  - yaml=0.1.7=h1de35cc_1001
  - zeromq=4.2.5=h0a44026_1006
  - zlib=1.2.11=h1de35cc_1004

